---
apiVersion: v1
kind: Service
metadata:
  name: jurisd
  namespace: jurisd
  labels:
    app.kubernetes.io/name: jurisd
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: jurisd
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
