import type { CommandContract } from "./types.js";

function flagName(name: string): string {
  return name.replace(/[A-Z]/g, (c) => `-${c.toLowerCase()}`);
}

function makeContract(
  id: string,
  cliName: string,
  mcpToolName: string,
  group: string,
  sideEffectClass: CommandContract["sideEffectClass"],
  positional: string[],
  numeric: string[],
  boolean: string[],
  array: string[],
  summary: string,
  synopsis: string,
): CommandContract {
  return {
    id,
    synopsis,
    summary,
    description: summary,
    stability: "stable",
    sideEffectClass,
    dangerous: false,
    requiresConfirmation: false,
    stdinMode: "none",
    outputModes: ["human", "json", "plain"],
    exitCodes: [0, 1, 2],
    resultContract: `${id}.v1`,
    capabilityGates: [],
    arguments: positional.map((name) => ({ name, required: true, summary: `${name} argument.` })),
    flags: [
      ...numeric.map((name) => ({
        name: flagName(name),
        type: "number" as const,
        summary: `${name} value.`,
      })),
      ...boolean.map((name) => ({
        name: flagName(name),
        type: "boolean" as const,
        summary: `${name} toggle.`,
      })),
      ...array.map((name) => ({ name, type: "array" as const, summary: `${name} values.` })),
    ],
    examples: [synopsis],
    adapters: {
      cli: {
        enabled: true,
        canonicalName: cliName,
        aliases: [cliName],
        positional,
        numeric,
        boolean,
        array,
        group,
      },
      mcp: { enabled: true, toolName: mcpToolName },
      tui: { enabled: false, label: summary.replace(/\.$/, "") },
    },
  };
}

function makeCliOnlyContract(
  id: string,
  cliName: string,
  group: string,
  sideEffectClass: CommandContract["sideEffectClass"],
  positional: string[],
  numeric: string[],
  boolean: string[],
  array: string[],
  summary: string,
  synopsis: string,
): CommandContract {
  return {
    id,
    synopsis,
    summary,
    description: summary,
    stability: "stable",
    sideEffectClass,
    dangerous: false,
    requiresConfirmation: false,
    stdinMode: "none",
    outputModes: ["human", "json", "plain"],
    exitCodes: [0, 1, 2],
    resultContract: `${id}.v1`,
    capabilityGates: [],
    arguments: positional.map((name) => ({ name, required: true, summary: `${name} argument.` })),
    flags: [
      ...numeric.map((name) => ({
        name: flagName(name),
        type: "number" as const,
        summary: `${name} value.`,
      })),
      ...boolean.map((name) => ({
        name: flagName(name),
        type: "boolean" as const,
        summary: `${name} toggle.`,
      })),
      ...array.map((name) => ({ name, type: "array" as const, summary: `${name} values.` })),
    ],
    examples: [synopsis],
    adapters: {
      cli: {
        enabled: true,
        canonicalName: cliName,
        aliases: [cliName],
        positional,
        numeric,
        boolean,
        array,
        group,
      },
      mcp: { enabled: false },
      tui: { enabled: false, label: summary.replace(/\.$/, "") },
    },
  };
}

export const COMMAND_CONTRACTS: CommandContract[] = [
  {
    id: "search.legislation",
    synopsis: "jurisd search legislation <query> [--jurisdiction cth] [--limit 10]",
    summary: "Search Australian and New Zealand legislation.",
    description: "Search legislation using the existing MCP search_legislation tool.",
    stability: "stable",
    sideEffectClass: "network_read",
    dangerous: false,
    requiresConfirmation: false,
    stdinMode: "none",
    outputModes: ["human", "json", "plain"],
    exitCodes: [0, 1, 2, 3, 4, 6],
    resultContract: "legal_search_results.v1",
    capabilityGates: [],
    arguments: [{ name: "query", required: true, summary: "Search query." }],
    flags: [
      { name: "jurisdiction", type: "string", summary: "Jurisdiction code." },
      { name: "limit", type: "number", summary: "Maximum result count." },
      { name: "offset", type: "number", summary: "Pagination offset." },
      { name: "format", type: "string", summary: "Output format." },
      { name: "sort-by", type: "string", summary: "Sort mode." },
      { name: "method", type: "string", summary: "Search method." },
    ],
    examples: ['jurisd search legislation "family violence" --jurisdiction nsw'],
    adapters: {
      cli: {
        enabled: true,
        canonicalName: "search-legislation",
        aliases: ["search-legislation"],
        positional: ["query"],
        numeric: ["limit", "offset"],
        boolean: [],
        array: [],
        group: "search",
      },
      mcp: { enabled: true, toolName: "search_legislation" },
      tui: { enabled: false, label: "Search legislation" },
    },
  },
  {
    id: "search.cases",
    synopsis: "jurisd search cases <query> [--jurisdiction cth] [--limit 10]",
    summary: "Search Australian and New Zealand case law.",
    description: "Search cases using the existing MCP search_cases tool.",
    stability: "stable",
    sideEffectClass: "network_read",
    dangerous: false,
    requiresConfirmation: false,
    stdinMode: "none",
    outputModes: ["human", "json", "plain"],
    exitCodes: [0, 1, 2, 3, 4, 6],
    resultContract: "legal_search_results.v1",
    capabilityGates: [],
    arguments: [{ name: "query", required: true, summary: "Search query." }],
    flags: [
      { name: "jurisdiction", type: "string", summary: "Jurisdiction code." },
      { name: "limit", type: "number", summary: "Maximum result count." },
      { name: "offset", type: "number", summary: "Pagination offset." },
      { name: "format", type: "string", summary: "Output format." },
      { name: "sort-by", type: "string", summary: "Sort mode." },
      { name: "method", type: "string", summary: "Search method." },
    ],
    examples: ['jurisd search cases "native title" --jurisdiction cth --limit 5'],
    adapters: {
      cli: {
        enabled: true,
        canonicalName: "search-cases",
        aliases: ["search-cases"],
        positional: ["query"],
        numeric: ["limit", "offset"],
        boolean: [],
        array: [],
        group: "search",
      },
      mcp: { enabled: true, toolName: "search_cases" },
      tui: { enabled: false, label: "Search cases" },
    },
  },
  makeContract(
    "source.fetchDocument",
    "fetch-document-text",
    "fetch_document_text",
    "source",
    "network_read",
    ["url"],
    [],
    [],
    [],
    "Fetch full text for a source document.",
    "jurisd fetch-document-text <url>",
  ),
  makeContract(
    "source.sourceLookup",
    "source-lookup",
    "source_lookup",
    "source",
    "network_read",
    [],
    ["articleId"],
    [],
    [],
    "Look up removed.invalid article metadata or citation URL.",
    "jurisd source-lookup --by citation --citation '[2008] NSWSC 323'",
  ),
  makeContract(
    "cite.format",
    "format-citation",
    "format_citation",
    "cite",
    "read_only_query",
    ["title"],
    ["footnoteRef", "pinpointPara", "pinpointPage", "paragraphNumber"],
    [],
    [],
    "Format an AGLC4 citation.",
    "jurisd format-citation 'Mabo v Queensland (No 2)' --neutral-citation '[1992] HCA 23'",
  ),
  makeContract(
    "cite.resolve",
    "resolve-citation",
    "resolve_citation",
    "cite",
    "network_read",
    ["citation"],
    [],
    [],
    [],
    "Resolve a citation to an authoritative source.",
    "jurisd resolve-citation '[1992] HCA 23'",
  ),
  makeContract(
    "cite.searchCitingCases",
    "search-citing-cases",
    "search_citing_cases",
    "cite",
    "network_read",
    ["caseName"],
    [],
    [],
    [],
    "Search for cases citing a named case.",
    "jurisd search-citing-cases 'Mabo v Queensland (No 2)'",
  ),
  makeContract(
    "cite.cacheCitedBy",
    "cache-cited-by",
    "cache_cited_by",
    "cite",
    "network_read",
    ["citeKey"],
    [],
    [],
    [],
    "Cache cited-by information for a citation key.",
    "jurisd cache-cited-by mabo-1992-hca-23",
  ),
  makeContract(
    "cite.create",
    "cite",
    "cite",
    "cite",
    "local_metadata_read",
    ["title"],
    ["year", "footnoteNumber"],
    [],
    ["keywords"],
    "Create or record a citation cache entry.",
    "jurisd cite 'Mabo v Queensland (No 2)' --year 1992",
  ),
  makeContract(
    "cite.bibliography",
    "bibliography",
    "bibliography",
    "cite",
    "local_metadata_read",
    [],
    [],
    [],
    [],
    "Render a bibliography from cached citations.",
    "jurisd bibliography",
  ),
  makeContract(
    "corpus.getProvision",
    "get-provision",
    "get_provision",
    "corpus",
    "local_metadata_read",
    ["act", "provision"],
    [],
    [],
    [],
    "Get a provision from an installed local data module.",
    "jurisd get-provision 'Family Law Act 1975 (Cth)' 's 60CC'",
  ),
  makeContract(
    "corpus.getActStructure",
    "get-act-structure",
    "get_act_structure",
    "corpus",
    "local_metadata_read",
    ["act"],
    ["depth"],
    [],
    [],
    "Get act structure from an installed local data module.",
    "jurisd get-act-structure 'Family Law Act 1975 (Cth)'",
  ),
  makeContract(
    "graph.findCiting",
    "find-citing",
    "find_citing",
    "graph",
    "local_metadata_read",
    ["target"],
    ["limit"],
    [],
    ["kinds"],
    "Find locally indexed items citing or considering a target.",
    "jurisd find-citing '[1992] HCA 23' --kinds cites,considers",
  ),
  makeContract(
    "search.semanticLocal",
    "semantic-search-local",
    "semantic_search_local",
    "search",
    "local_metadata_read",
    ["query"],
    ["k"],
    [],
    [],
    "Run local semantic search over installed data modules.",
    "jurisd semantic-search-local 'restraint of trade' --k 5",
  ),
  makeContract(
    "corpus.listDataModules",
    "list-data-modules",
    "list_data_modules",
    "corpus",
    "local_metadata_read",
    [],
    [],
    ["refresh", "includeInvalid"],
    [],
    "List installed local data modules.",
    "jurisd list-data-modules --include-invalid true",
  ),
  makeCliOnlyContract(
    "modules.fetch",
    "fetch-module",
    "modules",
    "filesystem_write",
    ["name"],
    [],
    [],
    [],
    "Fetch and install a data module.",
    "jurisd fetch-module <name>",
  ),
  makeCliOnlyContract(
    "modules.verify",
    "verify-module",
    "modules",
    "local_metadata_read",
    ["name"],
    [],
    [],
    [],
    "Verify an installed data module.",
    "jurisd verify-module <name>",
  ),
  makeCliOnlyContract(
    "modules.list",
    "list-modules",
    "modules",
    "local_metadata_read",
    [],
    [],
    [],
    [],
    "List installed data modules via the operator CLI.",
    "jurisd list-modules",
  ),
];

export function getCommandContractByCliName(name: string): CommandContract | undefined {
  return COMMAND_CONTRACTS.find(
    (contract) =>
      contract.adapters.cli.enabled &&
      (contract.adapters.cli.canonicalName === name ||
        contract.adapters.cli.aliases.includes(name)),
  );
}

export function getMcpBackedCommandContracts(): CommandContract[] {
  return COMMAND_CONTRACTS.filter((contract) => contract.adapters.mcp.enabled);
}
