import { COMMAND_CONTRACTS } from "./contracts.js";
import { SUPPORTED_COMPLETION_SHELLS } from "./completions.js";
import type { CommandContract } from "./types.js";

const GENERATED_NOTICE = "Generated by npm run generate:commands. Do not edit.";

function compareStable(a: string, b: string): number {
  if (a < b) return -1;
  if (a > b) return 1;
  return 0;
}

function cliContracts(contracts: CommandContract[]): CommandContract[] {
  return contracts
    .filter((contract) => contract.adapters.cli.enabled)
    .sort((a, b) => compareStable(cliName(a), cliName(b)));
}

function cliName(contract: CommandContract): string {
  return contract.adapters.cli.canonicalName ?? contract.id;
}

function markdownText(value: string): string {
  return value.replace(/\|/gu, "\\|").replace(/\s+/gu, " ").trim();
}

function inlineCode(value: string): string {
  return `\`${value.replace(/`/gu, "\\`")}\``;
}

function metadataLine(label: string, value: string): string {
  return `- ${label}: ${value}`;
}

function renderMarkdownTable(rows: string[][]): string[] {
  const widths = rows[0]!.map((_, column) => Math.max(...rows.map((row) => row[column]!.length)));
  const renderRow = (row: string[]): string =>
    `| ${row.map((cell, column) => cell.padEnd(widths[column]!)).join(" | ")} |`;
  const delimiter = `| ${widths.map((width) => "-".repeat(width)).join(" | ")} |`;
  const [header, ...body] = rows;
  return [renderRow(header!), delimiter, ...body.map(renderRow)];
}

function mcpToolReference(contract: CommandContract): string {
  if (!contract.adapters.mcp.enabled || !contract.adapters.mcp.toolName) return "not exposed";
  return inlineCode(contract.adapters.mcp.toolName);
}

function renderCommandSection(contract: CommandContract): string[] {
  const flags = contract.flags.length
    ? contract.flags.map(
        (flag) => `- ${inlineCode(`--${flag.name}`)} (${flag.type}): ${flag.summary}`,
      )
    : ["- none"];
  const args = contract.arguments.length
    ? contract.arguments.map((arg) => `- ${inlineCode(arg.name)}: ${arg.summary}`)
    : ["- none"];
  const examples = contract.examples.length
    ? contract.examples.map((example) => `- ${inlineCode(example)}`)
    : ["- none"];
  const mcpStatus = mcpToolReference(contract);

  return [
    `## ${inlineCode(cliName(contract))}`,
    "",
    contract.summary,
    "",
    metadataLine("Command id", inlineCode(contract.id)),
    metadataLine("Group", inlineCode(contract.adapters.cli.group)),
    metadataLine("Side effect", inlineCode(contract.sideEffectClass)),
    metadataLine("Stability", inlineCode(contract.stability)),
    metadataLine("MCP tool", mcpStatus),
    metadataLine("Result contract", inlineCode(contract.resultContract)),
    "",
    "Usage:",
    "",
    "```bash",
    contract.synopsis,
    "```",
    "",
    "Arguments:",
    "",
    ...args,
    "",
    "Flags:",
    "",
    ...flags,
    "",
    "Examples:",
    "",
    ...examples,
    "",
  ];
}

export function renderCommandReference(contracts: CommandContract[] = COMMAND_CONTRACTS): string {
  const commands = cliContracts(contracts);
  const table = renderMarkdownTable([
    ["Command", "Group", "Side effect", "MCP", "Summary"],
    ...commands.map((contract) => [
      inlineCode(cliName(contract)),
      inlineCode(contract.adapters.cli.group),
      inlineCode(contract.sideEffectClass),
      contract.adapters.mcp.enabled ? mcpToolReference(contract) : "CLI only",
      markdownText(contract.summary),
    ]),
  ]);

  return [
    `<!-- ${GENERATED_NOTICE} -->`,
    "",
    "# jurisd command reference",
    "",
    "This reference is generated from the command contract registry.",
    "",
    `Supported completion shells: ${SUPPORTED_COMPLETION_SHELLS.map(inlineCode).join(", ")}.`,
    "",
    "## Command summary",
    "",
    ...table,
    "",
    ...commands.flatMap(renderCommandSection),
  ].join("\n");
}
